# Generated by Django 4.2.17 on 2024-12-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_name',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.CharField(default='Default Product', max_length=255),
            preserve_default=False,
        ),
    ]
